# Generated by Django 5.0.1 on 2026-02-12 23:17

import apps.core.fields
import apps.projects.models.project_media
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Titre')),
                ('short_description', models.CharField(max_length=280, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Description courte')),
                ('full_description', models.TextField(validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Description complète')),
                ('stage', models.CharField(choices=[('IDEA', 'Idée'), ('PROTOTYPE', 'Prototype'), ('DEVELOPMENT', 'En développement'), ('GROWTH', 'En phase de croissance')], default='IDEA', max_length=20, verbose_name='Stade')),
                ('funding_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Financement minimum')),
                ('funding_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Financement maximum')),
                ('funding_currency', models.CharField(default='EUR', help_text='Code ISO de la devise (EUR, USD, etc.)', max_length=3, verbose_name='Devise')),
                ('location_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('location_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('is_premium', models.BooleanField(default=False, help_text='Projet avec fonctionnalités premium', verbose_name='Premium')),
                ('is_featured', models.BooleanField(default=False, help_text="Projet mis en avant sur la page d'accueil", verbose_name='Mis en avant')),
                ('is_draft', models.BooleanField(default=True, help_text="Projet en cours d'édition, non publié", verbose_name='Brouillon')),
                ('is_verified', models.BooleanField(default=False, help_text="Projet vérifié et validé par l'équipe administrative", verbose_name='Vérifié')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date à laquelle le projet a été vérifié', null=True, verbose_name='Date de vérification')),
                ('verification_notes', models.TextField(blank=True, help_text='Notes internes sur la vérification (visible uniquement aux administrateurs)', verbose_name='Notes de vérification')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('FUNDED', 'Financé'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('interests_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'intérêts")),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de favoris')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('reports_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de signalements')),
                ('is_flagged', models.BooleanField(default=False, help_text='Indique si le projet a été signalé par plusieurs utilisateurs', verbose_name='Signalé')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('business_plan', models.FileField(blank=True, help_text='Fichier PDF du business plan (Premium uniquement)', null=True, upload_to='projects/business_plans/%Y/%m/', verbose_name='Business plan')),
                ('video_url', models.URLField(blank=True, help_text="URL d'une vidéo de présentation (YouTube, Vimeo, etc.)", max_length=255, null=True, verbose_name='URL vidéo')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nom (EN)')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône dans la bibliothèque d'icônes", max_length=50, null=True, verbose_name='Icône')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie de projet',
                'verbose_name_plural': 'Catégories de projets',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('notes', models.TextField(blank=True, help_text='Notes personnelles sur ce projet', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Projet favori',
                'verbose_name_plural': 'Projets favoris',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInterest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('message', models.TextField(help_text="Message de présentation ou d'intérêt", verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VIEWED', 'Vu'), ('CONTACTED', 'Contacté'), ('NEGOTIATING', 'En négociation'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('is_anonymous', models.BooleanField(default=False, help_text="Indique si l'intérêt est exprimé de façon anonyme", verbose_name='Anonyme')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Montant que l'utilisateur est prêt à investir", max_digits=12, null=True, verbose_name="Montant d'investissement")),
                ('investment_currency', models.CharField(default='EUR', help_text='Code ISO de la devise (EUR, USD, etc.)', max_length=3, verbose_name='Devise')),
            ],
            options={
                'verbose_name': 'Intérêt pour un projet',
                'verbose_name_plural': 'Intérêts pour les projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('file', models.FileField(upload_to=apps.projects.models.project_media.project_media_upload_path, verbose_name='Fichier')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], default='IMAGE', max_length=20, verbose_name='Type de média')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_primary', models.BooleanField(default=False, help_text="Indique si cette image est l'image principale du projet", verbose_name='Image principale')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage du média", verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Média du projet',
                'verbose_name_plural': 'Médias du projet',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNeeds',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('resource_type', models.CharField(choices=[('INVESTMENT', 'Investissement'), ('LOAN', 'Prêt'), ('PARTNERSHIP', 'Partenariat'), ('EXPERTISE', 'Expertise'), ('MATERIAL', 'Matériel')], max_length=20, verbose_name='Type de ressource')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', apps.core.fields.MoneyField(blank=True, decimal_places=2, help_text='Montant financier requis (si applicable)', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('is_critical', models.BooleanField(default=False, help_text='Indique si ce besoin est critique pour le projet', verbose_name='Critique')),
                ('deadline', models.DateField(blank=True, help_text='Date limite pour satisfaire ce besoin', null=True, verbose_name='Date limite')),
                ('is_satisfied', models.BooleanField(default=False, help_text='Indique si ce besoin a été satisfait', verbose_name='Satisfait')),
            ],
            options={
                'verbose_name': 'Besoin du projet',
                'verbose_name_plural': 'Besoins du projet',
                'ordering': ['is_satisfied', 'is_critical', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('question', models.TextField(verbose_name='Question')),
                ('is_public', models.BooleanField(default=True, help_text='Indique si la question est visible par tous les utilisateurs', verbose_name='Public')),
                ('is_answered', models.BooleanField(default=False, help_text='Indique si la question a reçu une réponse', verbose_name='Répondu')),
            ],
            options={
                'verbose_name': 'Question sur le projet',
                'verbose_name_plural': 'Questions sur les projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectQuestionAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('answer', models.TextField(verbose_name='Réponse')),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses aux questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Contenu inapproprié'), ('SCAM', 'Arnaque'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Raison')),
                ('description', models.TextField(blank=True, help_text='Description facultative du problème constaté', verbose_name='Description')),
                ('is_resolved', models.BooleanField(default=False, help_text='Indique si le rapport a été traité par un administrateur', verbose_name='Résolu')),
            ],
            options={
                'verbose_name': 'Signalement de projet',
                'verbose_name_plural': 'Signalements de projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkillsNeeded',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='MEDIUM', max_length=20, verbose_name='Priorité')),
                ('required_level', models.PositiveSmallIntegerField(default=3, help_text='Niveau requis de 1 (débutant) à 5 (expert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Niveau requis')),
                ('is_satisfied', models.BooleanField(default=False, help_text='Indique si ce besoin en compétence a été satisfait', verbose_name='Satisfait')),
            ],
            options={
                'verbose_name': 'Compétence requise',
                'verbose_name_plural': 'Compétences requises',
                'ordering': ['is_satisfied', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('name_fr', models.CharField(max_length=50, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=50, verbose_name='Nom (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Tag de projet',
                'verbose_name_plural': 'Tags de projets',
                'ordering': ['name_fr'],
            },
        ),
    ]
