# Generated by Django 5.0.1 on 2026-02-12 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='project',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a vérifié le projet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_projects', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='projectinterest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_interests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectneeds',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_questions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='projectquestionanswer',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_question_answers', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par'),
        ),
        migrations.AddField(
            model_name='projectquestionanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='projects.projectquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='projectskillsneeded',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_needed', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.projecttag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='projectfavorite',
            index=models.Index(fields=['user'], name='projects_pr_user_id_811cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfavorite',
            index=models.Index(fields=['project'], name='projects_pr_project_47e76a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfavorite',
            unique_together={('user', 'project')},
        ),
        migrations.AddIndex(
            model_name='projectinterest',
            index=models.Index(fields=['user'], name='projects_pr_user_id_92935d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinterest',
            index=models.Index(fields=['project'], name='projects_pr_project_5f0d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinterest',
            index=models.Index(fields=['status'], name='projects_pr_status_856418_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectinterest',
            unique_together={('user', 'project')},
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['project'], name='projects_pr_project_e3a804_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['media_type'], name='projects_pr_media_t_6f7b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['is_primary'], name='projects_pr_is_prim_174cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectneeds',
            index=models.Index(fields=['project'], name='projects_pr_project_1eb403_idx'),
        ),
        migrations.AddIndex(
            model_name='projectneeds',
            index=models.Index(fields=['resource_type'], name='projects_pr_resourc_c11594_idx'),
        ),
        migrations.AddIndex(
            model_name='projectneeds',
            index=models.Index(fields=['is_critical'], name='projects_pr_is_crit_465c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectneeds',
            index=models.Index(fields=['is_satisfied'], name='projects_pr_is_sati_55255b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectquestion',
            index=models.Index(fields=['user'], name='projects_pr_user_id_57f24f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectquestion',
            index=models.Index(fields=['project'], name='projects_pr_project_bf0993_idx'),
        ),
        migrations.AddIndex(
            model_name='projectquestion',
            index=models.Index(fields=['is_public'], name='projects_pr_is_publ_71e0df_idx'),
        ),
        migrations.AddIndex(
            model_name='projectquestion',
            index=models.Index(fields=['is_answered'], name='projects_pr_is_answ_b14c18_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreport',
            index=models.Index(fields=['user'], name='projects_pr_user_id_a8a58b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreport',
            index=models.Index(fields=['project'], name='projects_pr_project_01b67a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectreport',
            index=models.Index(fields=['is_resolved'], name='projects_pr_is_reso_b87d23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectreport',
            unique_together={('user', 'project')},
        ),
        migrations.AddIndex(
            model_name='projectskillsneeded',
            index=models.Index(fields=['project'], name='projects_pr_project_a35b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectskillsneeded',
            index=models.Index(fields=['priority'], name='projects_pr_priorit_b49f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectskillsneeded',
            index=models.Index(fields=['is_satisfied'], name='projects_pr_is_sati_91e0b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectskillsneeded',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['creator'], name='projects_pr_creator_d605ca_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_30f4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['stage'], name='projects_pr_stage_c4babc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_draft'], name='projects_pr_is_draf_1be855_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_premium'], name='projects_pr_is_prem_e9648d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured'], name='projects_pr_is_feat_bfabaf_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_verified'], name='projects_pr_is_veri_48b6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['published_at'], name='projects_pr_publish_402983_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['verified_at'], name='projects_pr_verifie_60663d_idx'),
        ),
    ]
