# Generated by Django 5.0.1 on 2026-02-24 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-published_at'], name='projects_pr_publish_2cc856_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='projects_pr_status_b6b628_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'status'], name='projects_pr_categor_b7ef12_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_verified', 'status'], name='projects_pr_is_veri_14cef2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured', 'status'], name='projects_pr_is_feat_5f10f7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['location_country'], name='projects_pr_locatio_f726c2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['location_country', 'location_city'], name='projects_pr_locatio_04bac8_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='projects_pr_title_ba614c_idx'),
        ),
    ]
