# Generated by Django 5.2.1 on 2025-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires'),
        ),
    ]
