# Generated by Django 5.2.1 on 2025-06-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_comments_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Projet vérifié et validé par l'équipe administrative", verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='project',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes internes sur la vérification (visible uniquement aux administrateurs)', verbose_name='Notes de vérification'),
        ),
        migrations.AddField(
            model_name='project',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le projet a été vérifié', null=True, verbose_name='Date de vérification'),
        ),
        migrations.AddField(
            model_name='project',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a vérifié le projet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_projects', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_verified'], name='projects_pr_is_veri_48b6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['verified_at'], name='projects_pr_verifie_60663d_idx'),
        ),
    ]
