# Generated by Django 6.0.2 on 2026-02-26 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_projects_pr_created_775fe7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmedia',
            name='size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en bytes', null=True, verbose_name='Taille en bytes'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='Téléchargeur'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['uploader'], name='projects_pr_uploade_cbc716_idx'),
        ),
    ]
