# Generated by Django 5.2.1 on 2025-07-07 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_verified_project_verification_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Indique si le projet a été signalé par plusieurs utilisateurs', verbose_name='Signalé'),
        ),
        migrations.AddField(
            model_name='project',
            name='reports_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de signalements'),
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Contenu inapproprié'), ('SCAM', 'Arnaque'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Raison')),
                ('description', models.TextField(blank=True, help_text='Description facultative du problème constaté', verbose_name='Description')),
                ('is_resolved', models.BooleanField(default=False, help_text='Indique si le rapport a été traité par un administrateur', verbose_name='Résolu')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project', verbose_name='Projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Signalement de projet',
                'verbose_name_plural': 'Signalements de projet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='projects_pr_user_id_a8a58b_idx'), models.Index(fields=['project'], name='projects_pr_project_01b67a_idx'), models.Index(fields=['is_resolved'], name='projects_pr_is_reso_b87d23_idx')],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
