# Generated by Django 5.2.1 on 2025-05-21 22:50

import apps.core.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text="Montant de l'investissement", max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', help_text='Code ISO de la devise (EUR, USD, etc.)', max_length=3, verbose_name='Devise')),
                ('investment_type', models.CharField(choices=[('EQUITY', 'Actions'), ('LOAN', 'Prêt'), ('DONATION', 'Don'), ('CONVERTIBLE_NOTE', 'Note convertible')], default='EQUITY', max_length=20, verbose_name="Type d'investissement")),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage d'actions obtenues (si applicable)", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="Pourcentage d'actions")),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Taux d'intérêt annuel en pourcentage (si applicable)", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Taux d'intérêt")),
                ('term_months', models.PositiveIntegerField(blank=True, help_text='Durée du prêt en mois (si applicable)', null=True, verbose_name='Durée (mois)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Complété')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, help_text="Détails supplémentaires sur l'investissement", null=True, verbose_name='Description')),
                ('contract_file', models.FileField(blank=True, help_text="Document contractuel concernant l'investissement", null=True, upload_to='investments/contracts/%Y/%m/', verbose_name='Contrat')),
                ('notes', models.TextField(blank=True, help_text='Notes internes non visibles par les autres utilisateurs', null=True, verbose_name='Notes internes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Complété')], max_length=20, null=True, verbose_name='Ancien statut')),
                ('new_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Complété')], max_length=20, verbose_name='Nouveau statut')),
                ('comment', models.TextField(blank=True, help_text='Commentaire expliquant le changement', null=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': "Historique d'investissement",
                'verbose_name_plural': "Historiques d'investissements",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Montant du paiement', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', help_text='Code ISO de la devise (EUR, USD, etc.)', max_length=3, verbose_name='Devise')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Virement bancaire'), ('CREDIT_CARD', 'Carte de crédit'), ('PAYPAL', 'PayPal'), ('CRYPTO', 'Cryptomonnaie'), ('OTHER', 'Autre')], default='BANK_TRANSFER', max_length=20, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, help_text='Identifiant de la transaction (fourni par le processeur de paiement)', max_length=255, null=True, verbose_name='ID de transaction')),
                ('payment_details', models.JSONField(blank=True, help_text='Données supplémentaires liées au paiement', null=True, verbose_name='Détails du paiement')),
                ('receipt_file', models.FileField(blank=True, help_text='Reçu ou preuve de paiement', null=True, upload_to='investments/receipts/%Y/%m/', verbose_name='Reçu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
            ],
            options={
                'verbose_name': "Paiement d'investissement",
                'verbose_name_plural': "Paiements d'investissements",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Montant du remboursement', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('currency', models.CharField(default='EUR', help_text='Code ISO de la devise (EUR, USD, etc.)', max_length=3, verbose_name='Devise')),
                ('repayment_type', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('INTEREST', 'Intérêts'), ('DIVIDEND', 'Dividende'), ('MIXED', 'Mixte')], default='PRINCIPAL', max_length=20, verbose_name='Type de remboursement')),
                ('principal_amount', apps.core.fields.MoneyField(blank=True, decimal_places=2, help_text='Partie du montant correspondant au principal', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant principal')),
                ('interest_amount', apps.core.fields.MoneyField(blank=True, decimal_places=2, help_text='Partie du montant correspondant aux intérêts', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant des intérêts')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, help_text='Identifiant de la transaction (fourni par le processeur de paiement)', max_length=255, null=True, verbose_name='ID de transaction')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Virement bancaire'), ('CREDIT_CARD', 'Carte de crédit'), ('PAYPAL', 'PayPal'), ('CRYPTO', 'Cryptomonnaie'), ('OTHER', 'Autre')], default='BANK_TRANSFER', max_length=20, verbose_name='Méthode de paiement')),
                ('payment_details', models.JSONField(blank=True, help_text='Données supplémentaires liées au paiement', null=True, verbose_name='Détails du paiement')),
                ('receipt_file', models.FileField(blank=True, help_text='Reçu ou preuve de paiement', null=True, upload_to='investments/repayments/%Y/%m/', verbose_name='Reçu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('due_date', models.DateField(help_text='Date prévue pour le remboursement', verbose_name="Date d'échéance")),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Montant total du remboursement prévu', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total')),
                ('principal_amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Partie du montant correspondant au principal', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant principal')),
                ('interest_amount', apps.core.fields.MoneyField(decimal_places=2, help_text='Partie du montant correspondant aux intérêts', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant des intérêts')),
                ('currency', models.CharField(default='EUR', help_text='Code ISO de la devise (EUR, USD, etc.)', max_length=3, verbose_name='Devise')),
                ('is_paid', models.BooleanField(default=False, help_text='Indique si ce paiement programmé a été effectué', verbose_name='Payé')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Échéance de remboursement',
                'verbose_name_plural': 'Échéances de remboursement',
                'ordering': ['due_date'],
            },
        ),
    ]
