# Generated by Django 5.2.1 on 2025-05-21 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='Investisseur'),
        ),
        migrations.AddField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='investmenthistory',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='investments.investment', verbose_name='Investissement'),
        ),
        migrations.AddField(
            model_name='investmenthistory',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur ayant effectué le changement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_history_changes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='investmentpayment',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='investments.investment', verbose_name='Investissement'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='investments.investment', verbose_name='Investissement'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='paid_by',
            field=models.ForeignKey(help_text='Utilisateur ayant effectué le paiement (généralement le créateur du projet)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments_sent', to=settings.AUTH_USER_MODEL, verbose_name='Payé par'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='received_by',
            field=models.ForeignKey(help_text="Utilisateur ayant reçu le paiement (généralement l'investisseur)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments_received', to=settings.AUTH_USER_MODEL, verbose_name='Reçu par'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='investments.investment', verbose_name='Investissement'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='repayment',
            field=models.OneToOneField(blank=True, help_text='Remboursement associé à cette échéance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_item', to='investments.repayment', verbose_name='Remboursement'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investor'], name='investments_investo_6718df_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['project'], name='investments_project_07216f_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status'], name='investments_status_8a7490_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_type'], name='investments_investm_e7a1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenthistory',
            index=models.Index(fields=['investment'], name='investments_investm_c71c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenthistory',
            index=models.Index(fields=['user'], name='investments_user_id_223550_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpayment',
            index=models.Index(fields=['investment'], name='investments_investm_ac2f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpayment',
            index=models.Index(fields=['status'], name='investments_status_3748fa_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentpayment',
            index=models.Index(fields=['payment_method'], name='investments_payment_bc10fe_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['investment'], name='investments_investm_8659bb_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['status'], name='investments_status_cd22b2_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['repayment_type'], name='investments_repayme_d67a21_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['investment'], name='investments_investm_f5da5d_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['due_date'], name='investments_due_dat_b7ab9d_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['is_paid'], name='investments_is_paid_b8d916_idx'),
        ),
    ]
