# Generated by Django 5.2.1 on 2025-05-21 22:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('message_type', models.CharField(choices=[('TEXT', 'Texte'), ('IMAGE', 'Image'), ('FILE', 'Fichier'), ('AUDIO', 'Audio'), ('VIDEO', 'Vidéo'), ('LOCATION', 'Localisation'), ('SYSTEM', 'Système')], default='TEXT', max_length=20, verbose_name='Type')),
                ('content', models.TextField(help_text='Contenu du message (texte)', verbose_name='Contenu')),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('DELIVERED', 'Livré'), ('READ', 'Lu'), ('FAILED', 'Échec'), ('DELETED', 'Supprimé')], default='SENT', max_length=20, verbose_name='Statut')),
                ('is_system_message', models.BooleanField(default=False, help_text='Indique si le message est généré par le système', verbose_name='Message système')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('file', models.FileField(help_text='Fichier joint au message', upload_to='messages/attachments/%Y/%m/%d/', verbose_name='Fichier')),
                ('file_name', models.CharField(help_text="Nom d'origine du fichier", max_length=255, verbose_name='Nom du fichier')),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en octets', verbose_name='Taille')),
                ('file_type', models.CharField(help_text='Type MIME du fichier', max_length=100, verbose_name='Type MIME')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniature pour les images et vidéos', null=True, upload_to='messages/thumbnails/%Y/%m/%d/', verbose_name='Miniature')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('read_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de lecture du message', verbose_name='Lu à')),
            ],
            options={
                'verbose_name': 'Accusé de lecture',
                'verbose_name_plural': 'Accusés de lecture',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('title', models.CharField(blank=True, help_text='Titre facultatif de la conversation (obligatoire pour les groupes)', max_length=255, null=True, verbose_name='Titre')),
                ('conversation_type', models.CharField(choices=[('DIRECT', 'Message direct'), ('PROJECT', 'Discussion de projet'), ('GROUP', 'Groupe')], default='DIRECT', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archivée'), ('DELETED', 'Supprimée')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Date et heure du dernier message', null=True, verbose_name='Dernier message')),
                ('project', models.ForeignKey(blank=True, help_text='Projet associé à la conversation, si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='projects.project', verbose_name='Projet associé')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_admin', models.BooleanField(default=False, help_text="Indique si l'utilisateur est administrateur de la conversation", verbose_name='Administrateur')),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Date et heure de la dernière lecture des messages', null=True, verbose_name='Dernière lecture')),
                ('nickname', models.CharField(blank=True, help_text="Surnom personnalisé pour l'utilisateur dans cette conversation", max_length=100, null=True, verbose_name='Surnom')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archivée'), ('DELETED', 'Supprimée')], default='ACTIVE', help_text="Statut de l'utilisateur dans cette conversation", max_length=20, verbose_name='Statut')),
                ('muted_until', models.DateTimeField(blank=True, help_text="Date et heure jusqu'à laquelle la conversation est mise en sourdine", null=True, verbose_name="Muet jusqu'à")),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participants', to='messaging.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
