# Generated by Django 5.2.1 on 2025-06-14 02:27

import apps.content.models.publication
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('object_id', models.CharField(max_length=36, verbose_name="ID de l'objet")),
                ('content', models.TextField(help_text='Le contenu du commentaire (max 2000 caractères)', max_length=2000, verbose_name='Contenu')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de réponses')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le commentaire est visible', verbose_name='Actif')),
                ('is_edited', models.BooleanField(default=False, help_text='Indique si le commentaire a été modifié', verbose_name='Modifié')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Modifié le')),
                ('is_flagged', models.BooleanField(default=False, help_text='Commentaire signalé par des utilisateurs', verbose_name='Signalé')),
                ('flag_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de signalements')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment', verbose_name='Commentaire parent')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.comment', verbose_name='Commentaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'like de commentaire',
                'verbose_name_plural': 'likes de commentaires',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('title', models.CharField(help_text='Titre de la publication (10-200 caractères)', max_length=200, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Titre')),
                ('content', models.TextField(help_text='Contenu principal de la publication', validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Contenu')),
                ('summary', models.CharField(blank=True, help_text="Résumé court de la publication pour l'aperçu", max_length=300, null=True, verbose_name='Résumé')),
                ('publication_type', models.CharField(choices=[('EDUCATIONAL', 'Éducatif'), ('ENTERTAINING', 'Divertissant'), ('MOTIVATIONAL', 'Motivant'), ('INFORMATIONAL', 'Informatif'), ('TIPS', 'Conseils'), ('ADVERTISING', 'Publicitaire'), ('SPONSORED', 'Sponsorisé'), ('NEWS', 'Actualités'), ('TUTORIAL', 'Tutoriel'), ('CASE_STUDY', 'Étude de cas')], default='INFORMATIONAL', max_length=20, verbose_name='Type de publication')),
                ('domain', models.CharField(choices=[('PROJECT_MANAGEMENT', 'Gestion de projets'), ('FINANCE_INVESTMENT', 'Finances et investissements'), ('ENTREPRENEURSHIP', 'Entrepreneuriat'), ('PERSONAL_DEVELOPMENT', 'Développement personnel'), ('MARKETING_COMMUNICATION', 'Marketing et communication'), ('TECHNOLOGY', 'Technologie'), ('BUSINESS_STRATEGY', "Stratégie d'entreprise"), ('LEADERSHIP', 'Leadership'), ('INNOVATION', 'Innovation'), ('NETWORKING', 'Réseautage')], default='ENTREPRENEURSHIP', max_length=30, verbose_name='Domaine')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, null=True, verbose_name='Tags')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé'), ('SCHEDULED', 'Programmé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date et heure de publication', null=True, verbose_name='Date de publication')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Date et heure de publication programmée', null=True, verbose_name='Programmé pour')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de likes')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de partages')),
                ('is_featured', models.BooleanField(default=False, help_text="Publication mise en avant sur la page d'accueil", verbose_name='Mise en avant')),
                ('is_pinned', models.BooleanField(default=False, help_text='Publication épinglée en haut du fil', verbose_name='Épinglé')),
                ('allow_comments', models.BooleanField(default=True, help_text='Permet aux utilisateurs de commenter cette publication', verbose_name='Autoriser les commentaires')),
                ('is_sponsored', models.BooleanField(default=False, help_text="Indique si c'est un contenu sponsorisé", verbose_name='Contenu sponsorisé')),
                ('sponsor_name', models.CharField(blank=True, help_text="Nom de l'entreprise ou organisation sponsor", max_length=100, null=True, verbose_name='Nom du sponsor')),
                ('sponsor_url', models.URLField(blank=True, help_text='Site web du sponsor', null=True, verbose_name='URL du sponsor')),
                ('meta_description', models.CharField(blank=True, help_text='Description pour les moteurs de recherche', max_length=160, null=True, verbose_name='Meta description')),
                ('slug', models.SlugField(blank=True, help_text='URL slug pour la publication', max_length=250, null=True, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='authored_publications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.publication', verbose_name='Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'like de publication',
                'verbose_name_plural': 'likes de publication',
            },
        ),
        migrations.CreateModel(
            name='PublicationMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('file', models.FileField(help_text='Fichier média (image, vidéo, document, audio)', upload_to=apps.content.models.publication.publication_media_upload_path, verbose_name='Fichier')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio')], default='IMAGE', max_length=20, verbose_name='Type de média')),
                ('title', models.CharField(blank=True, help_text='Titre du média', max_length=100, null=True, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description du média', null=True, verbose_name='Description')),
                ('alt_text', models.CharField(blank=True, help_text="Texte alternatif pour l'accessibilité", max_length=255, null=True, verbose_name='Texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (0, 1, 2)", validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Ordre')),
                ('is_featured', models.BooleanField(default=False, help_text='Image utilisée comme couverture de la publication', verbose_name='Image de couverture')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True, verbose_name='Taille du fichier')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.publication', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'média de publication',
                'verbose_name_plural': 'médias de publication',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='content_com_content_859e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='content_com_author__a00d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='content_com_parent__b3cec5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_active'], name='content_com_is_acti_c26ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='content_com_created_7b7a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment'], name='content_com_comment_d48359_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user'], name='content_com_user_id_747aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['created_at'], name='content_com_created_e8120d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['author'], name='content_pub_author__f60072_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status'], name='content_pub_status_677646_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type'], name='content_pub_publica_ee96ab_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['domain'], name='content_pub_domain_d9700e_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['published_at'], name='content_pub_publish_b02219_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_featured'], name='content_pub_is_feat_54627b_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_pinned'], name='content_pub_is_pinn_fa4104_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_sponsored'], name='content_pub_is_spon_b0acc5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationlike',
            index=models.Index(fields=['publication'], name='content_pub_publica_c9d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationlike',
            index=models.Index(fields=['user'], name='content_pub_user_id_95820b_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationlike',
            index=models.Index(fields=['created_at'], name='content_pub_created_b7d010_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationlike',
            unique_together={('publication', 'user')},
        ),
        migrations.AddIndex(
            model_name='publicationmedia',
            index=models.Index(fields=['publication'], name='content_pub_publica_31b75c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationmedia',
            index=models.Index(fields=['media_type'], name='content_pub_media_t_a8a71a_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationmedia',
            index=models.Index(fields=['is_featured'], name='content_pub_is_feat_73bc14_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicationmedia',
            constraint=models.CheckConstraint(condition=models.Q(('order__lte', 2)), name='publication_media_max_3'),
        ),
    ]
