# Generated by Django 5.0.1 on 2026-02-12 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment', verbose_name='Commentaire parent'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.comment', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='authored_publications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='publicationlike',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.publication', verbose_name='Publication'),
        ),
        migrations.AddField(
            model_name='publicationlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='publicationmedia',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content.publication', verbose_name='Publication'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='content_com_content_859e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='content_com_author__a00d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='content_com_parent__b3cec5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_active'], name='content_com_is_acti_c26ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='content_com_created_7b7a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment'], name='content_com_comment_d48359_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user'], name='content_com_user_id_747aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['created_at'], name='content_com_created_e8120d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['author'], name='content_pub_author__f60072_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status'], name='content_pub_status_677646_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type'], name='content_pub_publica_ee96ab_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['domain'], name='content_pub_domain_d9700e_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['published_at'], name='content_pub_publish_b02219_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_featured'], name='content_pub_is_feat_54627b_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_pinned'], name='content_pub_is_pinn_fa4104_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_sponsored'], name='content_pub_is_spon_b0acc5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationlike',
            index=models.Index(fields=['publication'], name='content_pub_publica_c9d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationlike',
            index=models.Index(fields=['user'], name='content_pub_user_id_95820b_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationlike',
            index=models.Index(fields=['created_at'], name='content_pub_created_b7d010_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationlike',
            unique_together={('publication', 'user')},
        ),
        migrations.AddIndex(
            model_name='publicationmedia',
            index=models.Index(fields=['publication'], name='content_pub_publica_31b75c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationmedia',
            index=models.Index(fields=['media_type'], name='content_pub_media_t_a8a71a_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationmedia',
            index=models.Index(fields=['is_featured'], name='content_pub_is_feat_73bc14_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicationmedia',
            constraint=models.CheckConstraint(check=models.Q(('order__lte', 2)), name='publication_media_max_3'),
        ),
    ]
