# Generated by Django 5.2.1 on 2025-05-26 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK_CARD', 'Carte Bancaire'), ('BANK_TRANSFER', 'Virement Bancaire'), ('CASH', 'Espèces')], max_length=20, verbose_name='Type')),
                ('operator', models.CharField(blank=True, choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money'), ('EXPRESSU', 'Express Union')], max_length=20, null=True, verbose_name='Opérateur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('supported_currencies', models.JSONField(default=list, verbose_name='Devises supportées')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pourcentage de frais')),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais fixes')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(decimal_places=2, default=999999999, max_digits=15, verbose_name='Montant maximum')),
            ],
            options={
                'verbose_name': 'méthode de paiement',
                'verbose_name_plural': 'méthodes de paiement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_xaf', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix en XAF')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix en EUR')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix en USD')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel'), ('WEEKLY', 'Hebdomadaire'), ('DAILY', 'Quotidien')], max_length=20, verbose_name='Cycle de facturation')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name="Jours d'essai")),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Prix par défaut en XAF', max_digits=10, verbose_name='Prix par défaut')),
                ('currency', models.CharField(default='XAF', help_text='Devise par défaut', max_length=3, verbose_name='Devise par défaut')),
                ('duration_months', models.PositiveIntegerField(default=1, help_text="Durée de l'abonnement en mois", verbose_name='Durée en mois')),
                ('features', models.JSONField(default=list, verbose_name='Fonctionnalités')),
                ('max_projects', models.PositiveIntegerField(default=0, verbose_name='Nombre max de projets')),
                ('max_investments', models.PositiveIntegerField(default=0, verbose_name="Nombre max d'investissements")),
                ('priority_support', models.BooleanField(default=False, verbose_name='Support prioritaire')),
                ('advanced_analytics', models.BooleanField(default=False, verbose_name='Analyses avancées')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Populaire')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('external_plan_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID plan externe')),
            ],
            options={
                'verbose_name': 'plan de paiement',
                'verbose_name_plural': 'plans de paiement',
                'ordering': ['sort_order', 'price_xaf'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé'), ('PARTIALLY_REFUNDED', 'Partiellement remboursé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=30, verbose_name='Statut')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine facturation')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('EUR', 'Euro'), ('USD', 'Dollar US')], default='XAF', max_length=3, verbose_name='Devise de facturation')),
                ('external_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID abonnement externe')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('last_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_renewals', to='payments.payment', verbose_name='Dernier paiement')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_subscriptions', to='payments.paymentplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'abonnement de paiement',
                'verbose_name_plural': 'abonnements de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_e87164_idx'), models.Index(fields=['next_billing_date'], name='payments_pa_next_bi_e8c753_idx')],
            },
        ),
    ]
