# Generated by Django 5.2.1 on 2025-05-26 23:50
# Migration pour créer les modèles unifiés SubscriptionPlan et UserSubscription

import uuid
import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_paymentplan_paymentsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Création du modèle SubscriptionPlan unifié
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.CharField(help_text='Identifiant unique du plan (ex: basic_monthly, premium_yearly)', max_length=50, primary_key=True, serialize=False, verbose_name='ID du plan')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix en EUR')),
                ('price_xaf', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix en XAF')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix en USD')),
                ('duration_days', models.PositiveIntegerField(help_text="Durée de validité de l'abonnement en jours", verbose_name='Durée en jours')),
                ('features', models.JSONField(default=list, help_text='Liste des fonctionnalités incluses dans ce plan', verbose_name='Fonctionnalités')),
                ('max_projects', models.PositiveIntegerField(default=0, help_text='Nombre maximum de projets (0 = illimité)', verbose_name='Nombre max de projets')),
                ('max_investments', models.PositiveIntegerField(default=0, help_text="Nombre maximum d'investissements (0 = illimité)", verbose_name="Nombre max d'investissements")),
                ('max_messages', models.PositiveIntegerField(default=0, help_text='Nombre maximum de messages par mois (0 = illimité)', verbose_name='Nombre max de messages par mois')),
                ('ai_matching', models.BooleanField(default=False, help_text='Accès au système de matching par intelligence artificielle', verbose_name='Matching IA')),
                ('priority_support', models.BooleanField(default=False, help_text='Support client prioritaire', verbose_name='Support prioritaire')),
                ('advanced_analytics', models.BooleanField(default=False, help_text='Accès aux analyses et statistiques avancées', verbose_name='Analyses avancées')),
                ('custom_branding', models.BooleanField(default=False, help_text="Possibilité de personnaliser l'interface", verbose_name='Personnalisation marque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_popular', models.BooleanField(default=False, help_text='Marquer ce plan comme "plus populaire"', verbose_name='Plan populaire')),
                ('is_free', models.BooleanField(default=False, help_text='Plan gratuit (tous les prix doivent être 0)', verbose_name='Plan gratuit')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la liste (plus petit = premier)", verbose_name="Ordre d'affichage")),
                ('trial_days', models.PositiveIntegerField(default=0, help_text="Nombre de jours d'essai gratuit (0 = pas d'essai)", verbose_name="Jours d'essai gratuit")),
                ('mycoolpay_plan_id', models.CharField(blank=True, help_text='Identifiant du plan dans My-CoolPay', max_length=255, null=True, verbose_name='ID plan My-CoolPay')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires en format JSON', verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['sort_order', 'price_eur'],
            },
            bases=(apps.core.models.TimeStampedModel, models.Model),
        ),
        
        # Création du modèle UserSubscription unifié
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('PENDING', 'En attente'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé'), ('TRIAL', "Période d'essai"), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(help_text="Date de début de l'abonnement", verbose_name='Commencé le')),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration de l'abonnement", verbose_name='Expire le')),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text="Date de fin de la période d'essai gratuit", null=True, verbose_name="Fin de l'essai")),
                ('cancelled_at', models.DateTimeField(blank=True, help_text="Date d'annulation par l'utilisateur", null=True, verbose_name='Annulé le')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='Date de suspension (non-paiement, etc.)', null=True, verbose_name='Suspendu le')),
                ('auto_renew', models.BooleanField(default=True, help_text="L'abonnement se renouvelle automatiquement", verbose_name='Renouvellement automatique')),
                ('next_billing_date', models.DateTimeField(blank=True, help_text='Date de la prochaine facturation automatique', null=True, verbose_name='Prochaine facturation')),
                ('billing_currency', models.CharField(choices=[('EUR', 'Euro'), ('XAF', 'Franc CFA'), ('USD', 'Dollar US')], default='EUR', help_text='Devise utilisée pour les paiements de cet abonnement', max_length=3, verbose_name='Devise de facturation')),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Date du dernier paiement réussi', null=True, verbose_name='Dernier paiement')),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant du dernier paiement réussi', max_digits=10, null=True, verbose_name='Montant dernier paiement')),
                ('mycoolpay_subscription_id', models.CharField(blank=True, help_text="Identifiant de l'abonnement dans My-CoolPay", max_length=255, null=True, verbose_name='ID abonnement My-CoolPay')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires en format JSON', verbose_name='Métadonnées')),
                ('admin_notes', models.TextField(blank=True, help_text="Notes internes pour l'équipe support", verbose_name='Notes administratives')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptionplan', verbose_name="Plan d'abonnement")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement utilisateur',
                'verbose_name_plural': 'Abonnements utilisateurs',
                'ordering': ['-started_at'],
            },
            bases=(apps.core.models.TimeStampedModel, models.Model),
        ),
        
        # Ajout des index pour les performances
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active', 'sort_order'], name='payments_subscriptionplan_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_popular'], name='payments_subscriptionplan_popular_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='payments_usersubscription_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'expires_at'], name='payments_usersubscription_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['next_billing_date'], name='payments_usersubscription_billing_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['auto_renew', 'expires_at'], name='payments_usersubscription_autorenew_idx'),
        ),
    ]
