# Generated by Django 5.2.1 on 2025-05-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_unified_subscription_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscriptionplan',
            new_name='payments_su_is_acti_4cdb73_idx',
            old_name='payments_subscriptionplan_active_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionplan',
            new_name='payments_su_is_popu_40550d_idx',
            old_name='payments_subscriptionplan_popular_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='payments_us_user_id_7651b7_idx',
            old_name='payments_usersubscription_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='payments_us_status_5bda0b_idx',
            old_name='payments_usersubscription_status_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='payments_us_next_bi_308d6a_idx',
            old_name='payments_usersubscription_billing_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='payments_us_auto_re_31338d_idx',
            old_name='payments_usersubscription_autorenew_idx',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
