# Generated by Django 6.0.2 on 2026-03-26 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_preferred_categories', models.TextField(blank=True, default='[]', help_text="Liste des catégories préférées (ex: ['TECH', 'FINTECH'])", verbose_name='Catégories préférées')),
                ('min_investment_amount', models.DecimalField(decimal_places=2, default=0, help_text="Montant minimum d'investissement", max_digits=12, verbose_name="Montant minimum d'investissement")),
                ('max_investment_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Montant maximum d'investissement", max_digits=12, null=True, verbose_name="Montant maximum d'investissement")),
                ('_preferred_locations', models.TextField(blank=True, default='[]', help_text='Localisations préférées', verbose_name='Localisations préférées')),
                ('risk_tolerance', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=10, verbose_name='Tolérance au risque')),
                ('_viewed_projects', models.TextField(blank=True, default='[]', verbose_name='Projets consultés')),
                ('favorited_projects_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de projets en favoris')),
                ('invested_projects_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de projets investis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
