# Generated by Django 5.2.1 on 2025-06-06 11:50

import apps.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(default='#42B72A', max_length=7, validators=[apps.users.validators.validate_color_code], verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='domainexpertise',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message="Les années d'expérience ne peuvent pas être négatives"), django.core.validators.MaxValueValidator(80, message="Les années d'expérience semblent trop élevées")], verbose_name="Années d'expérience"),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez saisir une année valide au format YYYY (ex: 2023)', regex='^(19|20)\\d{2}$')], verbose_name='Année de fin'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Veuillez saisir une année valide au format YYYY (ex: 2023)', regex='^(19|20)\\d{2}$')], verbose_name='Année de début'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_facebook',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez saisir une URL Facebook valide (ex: https://www.facebook.com/username)', regex='^(https?:\\/\\/)?(www\\.)?facebook\\.com\\/[\\w\\-\\.]+\\/?$')], verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez saisir une URL LinkedIn valide (ex: https://www.linkedin.com/in/username)', regex='^(https?:\\/\\/)?(www\\.)?linkedin\\.com\\/in\\/[\\w\\-\\.]+\\/?$')], verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez saisir une URL Twitter valide (ex: https://twitter.com/username)', regex='^(https?:\\/\\/)?(www\\.)?twitter\\.com\\/[\\w\\-\\.]+\\/?$')], verbose_name='Twitter'),
        ),
    ]
