# Generated by Django 5.2.1 on 2025-06-14 00:17

import apps.users.models.company_profile
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_badge_icon_alter_badge_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('PERSONAL', 'Personnel'), ('BUSINESS', 'Entreprise')], default='PERSONAL', help_text="Indique s'il s'agit d'un compte personnel ou entreprise.", max_length=20, verbose_name='Type de compte'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison sociale')),
                ('registration_number', models.CharField(blank=True, help_text='SIRET, RCS, etc.', max_length=50, null=True, verbose_name="Numéro d'enregistrement")),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de TVA')),
                ('legal_form', models.CharField(blank=True, choices=[('SARL', 'SARL'), ('SAS', 'SAS'), ('SA', 'SA'), ('SNC', 'SNC'), ('EURL', 'EURL'), ('SASU', 'SASU'), ('EI', 'Entreprise Individuelle'), ('EIRL', 'EIRL'), ('AUTO_ENTREPRENEUR', 'Auto-entrepreneur'), ('ASSOCIATION', 'Association'), ('OTHER', 'Autre')], max_length=30, null=True, verbose_name='Forme juridique')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.users.models.company_profile.company_logo_upload_path, verbose_name="Logo de l'entreprise")),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name="Description de l'entreprise")),
                ('mission_statement', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mission')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité")),
                ('specialties', models.TextField(blank=True, max_length=500, null=True, verbose_name='Spécialités')),
                ('company_size', models.CharField(blank=True, choices=[('STARTUP', 'Startup (1-10 employés)'), ('SMALL', 'Petite entreprise (11-50 employés)'), ('MEDIUM', 'Entreprise moyenne (51-250 employés)'), ('LARGE', 'Grande entreprise (250+ employés)')], max_length=20, null=True, verbose_name="Taille de l'entreprise")),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name="Nombre d'employés")),
                ('company_stage', models.CharField(blank=True, choices=[('IDEA', 'Idée'), ('PROTOTYPE', 'Prototype'), ('MVP', 'MVP'), ('EARLY_STAGE', 'Stade précoce'), ('GROWTH', 'Croissance'), ('MATURE', 'Maturité')], max_length=20, null=True, verbose_name="Stade de l'entreprise")),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2030)], verbose_name='Année de création')),
                ('headquarters_address', models.TextField(blank=True, null=True, verbose_name='Adresse du siège social')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('linkedin_company', models.URLField(blank=True, null=True, verbose_name='LinkedIn Entreprise')),
                ('twitter_company', models.URLField(blank=True, null=True, verbose_name='Twitter Entreprise')),
                ('facebook_company', models.URLField(blank=True, null=True, verbose_name='Facebook Entreprise')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='En euros', max_digits=15, null=True, verbose_name="Chiffre d'affaires annuel")),
                ('funding_stage', models.CharField(blank=True, help_text='Amorçage, Série A, B, C, etc.', max_length=100, null=True, verbose_name='Stade de financement')),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, help_text='En euros', max_digits=15, null=True, verbose_name='Financement total levé')),
                ('is_verified', models.BooleanField(default=False, help_text="Indique si l'entreprise a été vérifiée par l'équipe VentureLink.", verbose_name='Entreprise vérifiée')),
                ('verification_documents', models.FileField(blank=True, help_text='Kbis, statuts, etc.', null=True, upload_to='company_verification/', verbose_name='Documents de vérification')),
                ('user', models.OneToOneField(limit_choices_to={'account_type': 'BUSINESS'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "profil d'entreprise",
                'verbose_name_plural': "profils d'entreprise",
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('role', models.CharField(choices=[('CEO', 'PDG/CEO'), ('CTO', 'Directeur Technique'), ('CFO', 'Directeur Financier'), ('CMO', 'Directeur Marketing'), ('COO', 'Directeur des Opérations'), ('FOUNDER', 'Fondateur'), ('CO_FOUNDER', 'Co-fondateur'), ('DIRECTOR', 'Directeur'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employé'), ('ADVISOR', 'Conseiller'), ('INVESTOR', 'Investisseur')], default='EMPLOYEE', max_length=20, verbose_name='Rôle')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre personnalisé')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('PENDING', 'En attente')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_admin', models.BooleanField(default=False, help_text="Peut gérer le profil de l'entreprise", verbose_name='Administrateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.companyprofile', verbose_name="Profil d'entreprise")),
            ],
            options={
                'verbose_name': "membre d'entreprise",
                'verbose_name_plural': "membres d'entreprise",
                'ordering': ['-is_admin', 'role', 'user__first_name'],
                'unique_together': {('company_profile', 'user')},
            },
        ),
    ]
