# Generated by Django 5.2.1 on 2025-06-06 11:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('new_users_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de nouveaux utilisateurs')),
                ('active_users_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisateurs actifs")),
                ('new_projects_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de nouveaux projets')),
                ('published_projects_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de projets publiés')),
                ('total_views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre total de vues')),
                ('total_interests_count', models.PositiveIntegerField(default=0, verbose_name="Nombre total d'intérêts exprimés")),
                ('total_investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total investi')),
                ('new_subscriptions_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de nouveaux abonnements')),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Revenus des abonnements')),
            ],
            options={
                'verbose_name': 'Métriques quotidiennes',
                'verbose_name_plural': 'Métriques quotidiennes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralTracker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Source')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Site référent')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM Content')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='Action réalisée')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Suivi de référencement',
                'verbose_name_plural': 'Suivi de référencement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_created_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de projets créés')),
                ('projects_published_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de projets publiés')),
                ('total_project_views', models.PositiveIntegerField(default=0, verbose_name='Nombre total de vues sur les projets')),
                ('total_project_interests', models.PositiveIntegerField(default=0, verbose_name="Nombre total d'intérêts exprimés pour les projets")),
                ('total_comments_received', models.PositiveIntegerField(default=0, verbose_name='Nombre total de commentaires reçus')),
                ('investments_made_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'investissements réalisés")),
                ('total_investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total investi')),
                ('messages_sent_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de messages envoyés')),
                ('messages_received_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de messages reçus')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de connexions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Métriques utilisateur',
                'verbose_name_plural': 'Métriques utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROJECT_VIEW', 'Vue de projet'), ('PROJECT_INTEREST', 'Intérêt pour un projet'), ('PROJECT_FAVORITE', 'Ajout aux favoris'), ('PROJECT_COMMENT', 'Commentaire sur un projet'), ('PROJECT_SHARE', 'Partage de projet'), ('USER_LOGIN', 'Connexion utilisateur'), ('USER_REGISTRATION', 'Inscription utilisateur'), ('INVESTMENT_MADE', 'Investissement réalisé'), ('MESSAGE_SENT', 'Message envoyé'), ('SUBSCRIPTION_STARTED', 'Abonnement démarré'), ('SUBSCRIPTION_RENEWED', 'Abonnement renouvelé'), ('SUBSCRIPTION_CANCELED', 'Abonnement annulé')], max_length=50, verbose_name="Type d'événement")),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'événement",
                'verbose_name_plural': "Journal d'événements",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_e_created_08fa78_idx'), models.Index(fields=['event_type'], name='analytics_e_event_t_d9b9a1_idx'), models.Index(fields=['user'], name='analytics_e_user_id_cf2861_idx'), models.Index(fields=['content_type', 'object_id'], name='analytics_e_content_1c347e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(verbose_name="ID de l'objet")),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('interest_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'intérêts exprimés")),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de favoris')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de partages')),
                ('investment_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'investissements")),
                ('total_investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total investi')),
                ('view_to_interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de conversion vues/intérêts (%)')),
                ('interest_to_investment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de conversion intérêts/investissements (%)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
            ],
            options={
                'verbose_name': 'Métriques projet',
                'verbose_name_plural': 'Métriques projets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='analytics_p_content_ef1acc_idx')],
            },
        ),
    ]
