# Generated by Django 5.0.1 on 2026-02-12 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.CharField(help_text='Code unique pour identifier le modèle', max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('category', models.CharField(choices=[('GENERAL', 'Général'), ('PROJECT', 'Projet'), ('INVESTMENT', 'Investissement'), ('MESSAGE', 'Message'), ('PAYMENT', 'Paiement'), ('SYSTEM', 'Système')], default='GENERAL', max_length=20, verbose_name='Catégorie')),
                ('title_template', models.CharField(help_text='Modèle de titre avec placeholders (ex: "Nouveau message de {sender_name}")', max_length=255, verbose_name='Modèle de titre')),
                ('content_template', models.TextField(help_text='Modèle de contenu avec placeholders', verbose_name='Modèle de contenu')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('NORMAL', 'Normale'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Priorité')),
                ('default_icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône par défaut')),
                ('default_delivery_methods', models.CharField(default='APP', help_text='Méthodes de livraison séparées par des virgules', max_length=255, verbose_name='Méthodes de livraison par défaut')),
                ('description', models.TextField(blank=True, help_text="Description de l'utilisation du modèle", null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Si désactivé, ce modèle ne sera pas utilisé', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Modèle de notification',
                'verbose_name_plural': 'Modèles de notification',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NotificationUserPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('enable_email', models.BooleanField(default=True, verbose_name='Activer les emails')),
                ('enable_push', models.BooleanField(default=True, verbose_name='Activer les notifications push')),
                ('enable_sms', models.BooleanField(default=False, verbose_name='Activer les SMS')),
                ('enable_app', models.BooleanField(default=True, verbose_name="Activer les notifications dans l'application")),
                ('project_notifications', models.BooleanField(default=True, verbose_name='Notifications de projet')),
                ('investment_notifications', models.BooleanField(default=True, verbose_name="Notifications d'investissement")),
                ('message_notifications', models.BooleanField(default=True, verbose_name='Notifications de message')),
                ('payment_notifications', models.BooleanField(default=True, verbose_name='Notifications de paiement')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Notifications système')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Début des heures silencieuses')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin des heures silencieuses')),
                ('minimum_priority', models.CharField(choices=[('LOW', 'Basse'), ('NORMAL', 'Normale'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='LOW', help_text='Priorité minimale des notifications à recevoir', max_length=10, verbose_name='Priorité minimale')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('category', models.CharField(choices=[('GENERAL', 'Général'), ('PROJECT', 'Projet'), ('INVESTMENT', 'Investissement'), ('MESSAGE', 'Message'), ('PAYMENT', 'Paiement'), ('SYSTEM', 'Système')], default='GENERAL', max_length=20, verbose_name='Catégorie')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('NORMAL', 'Normale'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('UNREAD', 'Non lue'), ('READ', 'Lue'), ('ARCHIVED', 'Archivée'), ('DELETED', 'Supprimée')], default='UNREAD', max_length=10, verbose_name='Statut')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('delivery_methods', models.CharField(default='APP', help_text='Méthodes de livraison séparées par des virgules', max_length=255, verbose_name='Méthodes de livraison')),
                ('delivered', models.BooleanField(default=False, verbose_name='Livrée')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name="ID de l'objet")),
                ('action_url', models.CharField(blank=True, help_text="URL où rediriger l'utilisateur quand il clique sur la notification", max_length=255, null=True, verbose_name="URL d'action")),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône à afficher", max_length=50, null=True, verbose_name='Icône')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
